protected/controllers/UserController.php
<?php

namespace app\controllers;

use app\components\TActiveForm;
use app\components\TController;
use app\models\Driver;
use app\models\EmailQueue;
use app\models\LoginForm;
use app\models\User;
use app\models\UserAddress;
use app\models\search\UserSearch;
use Yii;
use pheme\grid\actions\ToggleAction;
use yii\filters\AccessControl;
use yii\filters\AccessRule;
use yii\httpclient\Exception;
use yii\web\BadRequestHttpException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;
use app\models\Company;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends TController
{

    public $enableCsrfValidation = FALSE;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className()
                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'view',
                            'editabledemo',
                            'update-admin',
                            'update-customer',
                            'update-driver',
                            'delete',
                            'delete-driver',
                            'reset',
                            'login',
                            'logout',
                            'changepassword',
                            'resetpassword',
                            'profilepic',
                            'toggle',
                            'download',
                            'clear',
                            'update-admin',
                            'dashboard',
                            'recover',
                            'add-admin',
                            'image-manager',
                            'image-upload',
                            'profile',
                            'profile-update',
                            'driver',
                            'ajax'
                        ],
                        'allow' => true,
                        'matchCallback' => function () {
                            return User::isAdmin();
                        }
                    ],
                    [
                        'actions' => [
                            'login',
                            'logout',
                            'signup',
                            'reset',
                            'recover',
                            'changepassword',
                            'resetpassword',
                            'profilepic',
                            'download',
                            'clear-data',
                            'test-email',
                        ],
                        'allow' => true,
                        'roles' => [
                            '?',
                            '*'
                        ]
                    ]
                ]
            ],
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'delete' => [
                        'post'
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function onAuthSuccess($client)
    {
        (new AuthHandler($client))->handle();
    }

    public function actions()
    {
        return [
            'toggle' => [
                'class' => ToggleAction::className(),
                'modelClass' => 'app\models\search\UserSearch',
                'setFlash' => true
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [
                    $this,
                    'onAuthSuccess'
                ]
            ]
        ];
    }

    public function actionDownload($image_file)
    {
        $file = UPLOAD_PATH . $image_file;

        if (file_exists($file)) {

            Yii::$app->response->sendFile($file);
        }
        return false;
    }

    public function actionClear()
    {
        $runtime = Yii::getAlias('@runtime');
        $this->cleanRuntimeDir($runtime);

        $this->cleanAssetsDir();
        return $this->goBack();
    }

    public function actionIndex()
    {
        $this->layout = 'main';
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 20;
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);
    }

    public function actionDriver()
    {
        $this->layout = 'main';
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchDriver(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 20;
        return $this->render('driver_grid', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);
    }

    public function actionAddAdmin()
    {
        $this->layout = 'registration';
        $count = User::find()->count();
        if ($count == 0) {
            $model = new User();
            if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                $model->scenario = 'signup';
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->load(Yii::$app->request->post())) {
                $model->scenario = 'signup';
                $model->role_id = User::ROLE_ADMIN;
                $model->state_id = User::STATE_ACTIVE;

                if ($model->save()) {
                    $model->setPassword($model->password);
                    return $this->redirect([
                                'login'
                    ]);
                }
            } else {
                return $this->render('signup', [
                            'model' => $model
                ]);
            }
        } else {
            return $this->redirect();
        }
    }

    /*
     * public function actionGetName(){
     *
     * }
     */

    /**
     * Displays a single User model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (!($model->isAllowed()))
            throw new HttpException(403, Yii::t('app', 'You are not allowed to access this page.'));
        $user_address = UserAddress::find()->where([
                    'create_user_id' => $id
                ])->all();
        $address_array = [];
        if ($user_address) {
            foreach ($user_address as $address) {
                $address_array[] = [
                    'attribute' => $address->getTypeOptions($address->type_id) . ' Address',
                    'value' => $address->title
                ];
            }
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                        'view',
                        'id' => $model->id
            ]);
        }
        $this->updateMenuItems($model);
        return $this->render('view', [
                    'model' => $model,
                    'user_address' => $address_array
        ]);
    }

    public function actionProfile($id)
    {
        $model = $this->findModel($id);

        return $this->render('profile', [
                    'model' => $model
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionAdd()
    {
        $this->layout = 'main';
        $model = new User();
        $model->role_id = User::ROLE_ADMIN;
        $model->state_id = User::STATE_ACTIVE;
        if ($model->load(Yii::$app->request->post())) {
            $model->saveUploadedFile($model, 'image_file');
            if ($model->save()) {
                $model->generatePasswordResetToken();
                $email = $model->email;

                $view = 'sendPassword';
                $sub = "Your Account is created  at: " . \Yii::$app->params['company'];

                $sendMessage = \Yii::$app->controller->renderPartial('/../mail/sendPassword', [
                    'user' => $email
                ]);
                $emailQueue = new EmailQueue();
                $emailQueue->sendNow($email, $sendMessage, \Yii::$app->params['adminEmail'], $sub);

                Yii::$app->getSession()->setFlash('success', ' User Added Successfully.');
                return $this->redirect([
                            'view',
                            'id' => $model->id
                ]);
            }
        }
        return $this->render('create', [
                    'model' => $model
        ]);
    }

    public function actionRecover()
    {
        $this->layout = 'guest-main';
        $model = new User([
            'scenario' => 'token_request'
        ]);
        $emailQueue = new EmailQueue();
        if (isset($_POST['User'])) {
            $email = trim($_POST['User']['email']);
            $user = User::findOne([
                        'email' => $email
            ]);

            if ($user) {
                $user->generatePasswordResetToken();
                if (!$user->save()) {
                    throw new Exception("Cant Generate Authentication Key");
                }

                $email = $user->email;
                $view = "passwordResetToken";

protected/views/user/Change.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
?>

<section class="content-header">
	<h1><?php echo Html::encode(Html::valueEx($model)); ?></h1>
</section>

<div class="content">
	<div class="content-header">
		<h3 class="sub-history box-title">
			<span>Change Password</span>
		</h3>
		<div class="clearfix"></div>
		<br>

		<div class="clearfix"></div>
	</div>
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title"></h3>
		</div>

		<div class="box-body">
			<div class="col-md-8">
		<?php if(Yii::$app->user->hasFlash('danger')): ?>
			<div class="alert alert-danger">
					<div class="flash-success">
				<?php echo Yii::$app->user->getFlash('danger');  ?>
				</div>
				</div>

			<?php endif;?>

			<?php if(Yii::$app->user->hasFlash('success')): ?>
			<div class="alert alert-success">
					<div class="flash-success">
				<?php echo Yii::$app->user->getFlash('success'); ?>
				</div>
				</div>

			<?php endif;?>
			<?php
			
$form = $this->beginWidget ( 'booster.widgets.TbActiveForm', array (
					'id' => 'user-form',
					'enableAjaxValidation' => true,
					'enableClientValidation' => true,
					'clientOptions' => array (
							'validateOnSubmit' => true 
					),
					
					// 'action'=>Yii::app()->createUrl('api/user/changepassword'),
					'htmlOptions' => array (
							'enctype' => 'multipart/form-data' 
					) 
			) );
			?>
			<p class="help-block form-group text-right">
			<?php echo Yii::t('app', 'Fields with'); ?>
				<span class="required">*</span>
				<?php echo Yii::t('app', 'are required'); ?>
				.
			</p>
				<div class="clearfix"></div>
				<div class="form-group">
			<?php echo $form->textFieldGroup($model,'email',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'form-control','maxlength'=>128,'placeHolder'=>'Email','readOnly'=>true)))); ?>

			</div>

				<div class="form-group">
			<?php echo $form->passwordFieldGroup($model, 'password', array('placeHolder'=>$model->getAttributeLabel('password'),'class'=>'form-control')); ?>
			
			</div>


				<div class="form-group">
			<?php echo $form->passwordFieldGroup($model, 'password_2', array('placeHolder'=>$model->getAttributeLabel('password_2'),'class'=>'form-control')); ?>
			
			</div>
				<div class="form-group">
					<div class=" ">
				<?php
				$this->widget ( 'booster.widgets.TbButton', array (
						'buttonType' => 'submit',
						'context' => 'info',
						'label' => ' Save ' 
				)
				 );
				?>
				</div>
				</div>
			<?php $this->endWidget(); ?>
</div>
			<div class="clearfix"></div>

		</div>
	</div>
</div>

protected/views/user/_form.php
<?php
use app\components\TActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel">
	<div class="panel-body">

    <?php
				$form = TActiveForm::begin ( [ 
						'layout' => 'horizontal',
						'id' => 'user-form',
						'options' => [ 
								'enctype' => 'multipart/form-data' 
						] 
				
				] );
				?>
    
    <?= $form->field($model, 'first_name')->textInput(['maxlength' => 55])?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => 55])?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 128])?>

    <?= $form->field($model, 'contact_no')->textInput(['maxlength' => 11])?>  

   <?= $form->field ( $model, 'image_file', [ 'enableAjaxValidation' => false,'enableClientValidation' => true ])->fileInput()?>

   
 
    <div
			class="col-md-6 col-md-offset-3 bottom-admin-button btn-space-bottom">
			<div class="form-group text-center">
	        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Add') : Yii::t('app', 'Update'), ['id'=>'user-form-submit','class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-success'])?>
	    </div>
		</div>
    <?php TActiveForm::end(); ?>
    <div class="clearfix"></div>
	</div>
</div>

protected/views/user/_grid.php
<?php
use app\components\TGridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

Pjax::begin();

/**
 *
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\User $searchModel
 */
$this->title = Yii::t('app', 'Customer') . ' - Index | ' . Yii::$app->name;
?>
<style>
.FullName {
	text-transform: capitalize;
}
</style>
<?php Pjax::begin(); ?>
    <?php
    
    echo TGridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => [
            'class' => 'table table-bordered table-hover'
        ],
        'filterModel' => $searchModel,
        'emptyText' => '<i>No Customer Found</i>',
        'columns' => [
            'id',
            [
                'attribute' => 'first_name',
                'contentOptions' => [
                    'class' => 'FullName'
                ],
                'value' => 'first_name'
            
            ],
            [
                'attribute' => 'last_name',
                'contentOptions' => [
                    'class' => 'FullName'
                ],
                'value' => 'last_name'
            
            ],
            [
                'attribute' => 'state_id',
                'format' => 'raw',
                'filter' => isset($searchModel) ? $searchModel->getStateOptions() : null,
                'value' => function ($data) {
                    return $data->getStateBadge();
                }
            ],
            'email:email',
            'contact_no',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => '<a>Actions</a>',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', [
                            
                            '/user/update-customer',
                            
                            'id' => $model->id
                        ], [
                            'title' => 'Update'
                        ]);
                    }
                ]
            ]
        ]
    ]);
    ?>
<?php Pjax::end(); ?>

protected/views/user/changepassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

//$this->title = 'Change Password';
$this->params ['breadcrumbs'] [] = (string)$model;
?>
<?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error')?>
</div>
<?php endif; ?>

		<?=  \app\components\PageHeader::widget([
		'title' => 'Change Password'
]); ?>
	
	<div class="wrapper">
	<div class="panel">
	<header class="panel-heading"> Please fill out the following fields to
			change password : </header>
	<div class="panel-body change-pass-outer">	
<div class=" col-md-8 col-md-offset-2">
	<div class="site-changepassword">
	
  
    <?php
				
$form = ActiveForm::begin ( [ 
						'id' => 'changepassword-form',
						'options' => [ 
								'class' => 'form-horizontal' 
						],
						'fieldConfig' => [ 
								'template' => "{label}\n<div class=\"col-lg-8\">
                        {input}</div>\n<div class=\"col-md-6 col-md-offset-4\">
                        {error}</div>",
								'labelOptions' => [ 
										'class' => 'col-lg-4 control-label' 
								] 
						],
	//	'action'=>['api/user/change-password'],
				] );
				?>
        
     <?= $form->field($model,'oldPassword',['inputOptions'=>[
            'placeholder'=>'','value'=>'']])->label()->passwordInput() ?>
            
            <?= $form->field($model,'newPassword',['inputOptions'=>[
            'placeholder'=>'','value'=>'']])->label()->passwordInput() ?>
         
       
        <?= $form->field($model,'confirm_password',['inputOptions'=>[
            'placeholder'=>'']])->label()->passwordInput() ?>
       
        <div class="form-group">
		<div class="col-lg-12 text-right">
                <?=Html::submitButton ( 'Change password', [ 'class' => 'btn btn-success' ] )?>
            </div>
	</div>
    <?php ActiveForm::end(); ?>
</div>
	
</div>
</div>
</div>
</div>

protected/views/user/driver_index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */
// $this->title = Yii::t ( 'app', 'Customers' );
$this->title = Yii::t ( 'app', 'Driver' ) . ' - Index | ' . Yii::$app->name;
$this->params ['breadcrumbs'] [] = $this->title;
?>
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error')?>
</div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>
<div class="wrapper">
	<div class="user-index">
		<div class=" panel ">


	<?= \app\components\PageHeader::widget( ['title'=>Yii::t ( 'app', 'Customers' )] ); ?>
	</div>
	</div>
	<div class="panel panel-margin">
			<div class="panel-body">
				<div class="content-section clearfix">
		<?php echo $this->render('driver_grid', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]); ?>
	</div>
	</div>
</div>
</div>

protected/views/user/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */
// $this->title = Yii::t ( 'app', 'Customers' );
$this->params ['breadcrumbs'] [] = [ 
		'label' => Yii::t ( 'app', 'Customers' ),
		'url' => [ 
				'index' 
		] 
];
$this->params ['breadcrumbs'] [] = Yii::t ( 'app', 'Index' );
?>
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error')?>
</div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>
<div class="wrapper">
	<div class="user-index">
		<div class=" panel ">

	<?= \app\components\PageHeader::widget( ['title'=>Yii::t ( 'app', 'Customers' )] ); ?>
	</div>
	</div>
	
	<div class="panel panel-margin">
			<div class="panel-body">
				<div class="content-section clearfix">
		<?php echo $this->render('_grid', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]); ?>
	</div>
	</div>
</div>
</div>

protected/views/user/login.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

//$this->title = 'Sign In';

$fieldOptions1 = [ 
		'options' => [ 
				'class' => 'form-group has-feedback' 
		],
		
		'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>" 
];

$fieldOptions2 = [ 
		'options' => [ 
				'class' => 'form-group has-feedback' 
		],
		'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>" 
];
?>

<style>
.checkbox, .radio {
  margin-top:0px;
}
</style>
<div class="login_form clearfix col-md-4 col-sm-6 col-xs-12 login-design">
	<?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>
		<h1 class="text-center white">Login</h1>
<div class="form-signin" >
              <?php
														
$form = ActiveForm::begin ( [ 
																'id' => 'login-form',
																// 'enableClientValidation' => false,
																'options' => [ 
																		'class' => 'form-signin' 
																],
																/* 'action' => [ 
																		'api/user/login' 
																] */ 
														] );
														?>
     
         <?=$form->field ( $model, 'username', $fieldOptions1 )->label ( false )->textInput ( [ 'placeholder' => $model->getAttributeLabel ( 'email' ) ] )?>
         <?=$form->field ( $model, 'password', $fieldOptions2 )->label ( false )->passwordInput ( [ 'placeholder' => $model->getAttributeLabel ( 'password' ) ] )?>
       
                 
                 
        <?= Html::submitButton('Login', ['class' => 'btn btn-lg btn-success btn-block', 'name' => 'login-button'])?>
              
                  
			
			<div class="row">
				<div class="col-md-6 text-left">
					<div class="checkbox remember">
					<?php echo $form->field($model, 'rememberMe')->checkbox();?>

					</div>
				</div>
			
			
			<div class="col-md-6">
			<a class="pull-right forgot"
			data-toggle="modal"
			href="<?php echo Url::toRoute(['user/recover'])?>"> Forgot Password?</a></div>
		
		 </div>
		</div>

</div>		
	</div>
<?php \yii\bootstrap\ActiveForm::end()?>
	


</div>
</div>
</div>

protected/views/user/profile.php
<?php
/**
 *@copyright : ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 *@author	 : Shiv Charan Panjeta < shiv@toxsl.com >
 */
use app\components\PageHeader;
use app\components\TDetailView;
use app\components\useraction\UserAction;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\User */

// $this->title = $model->id;

$this->params ['breadcrumbs'] [] = ([ 
		'label' => $model->full_name 
]);

?>

<div class="wrapper">
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error')?>
</div>
<?php endif; ?>

<?php

if (Yii::$app->session->hasFlash ( 'success' )) :
	?>

<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>


	<div class=" panel ">
		<?php echo  PageHeader::widget(['title'=>$model->first_name,'model'=>$model]); ?><div
			class="custom-view-button">
			<a href="<?=Url::toRoute(['user/update-admin','id'=>$model->id])?>"
				class="btn btn-success">Update</a>
		</div>

	</div>
	<div class=" panel ">
		<div class=" panel-body ">
			<div class="col-md-2">
				<p>						
        			 <?php
												if (! empty ( $model->image_file )) {
													echo Html::img ( [ 
															'user/download',
															'image_file' => $model->image_file 
													], [ 
															'height' => '150',
															'width' => '150' 
													] );
												} else {
													echo Html::img ( [ 
															'themes/green/img/default.png' 
													], [ 
															'height' => '150',
															'width' => '150' 
													] );
												}
												?>
   			 		</p>

			</div>
			<div class="col-md-10">
   				 <?php
								
								echo TDetailView::widget ( [ 
										'model' => $model,
										'attributes' => [ 
												'id',
												'full_name',
												'email:email',
												'contact_no',
												[ 
														'attribute' => 'state',
														'format' => 'raw',
														'value' => $model->getStateBadge () 
												] 
											
											/*
										 * [
										 * 'attribute' => 'role_id',
										 * 'visible' => ($model->role_id== User::ROLE_PASSENGER ||$model->role_id== User::ROLE_DRIVER ) ? true : false,
										 * 'format' => 'raw',
										 * 'value' => $model->getRoleOptions ( $model->role_id )
										 * ],
										 */
											// 'created_o:datetime'
										] 
								] )?>
		</div>

		</div>
		<div>
				<?php
				echo UserAction::widget ( [ 
						'model' => $model,
						'attribute' => 'state_id',
						'states' => $model->getStateOptions () 
				] );
				?>	
			</div>



	</div>



</div>

protected/views/user/requestPasswordResetToken.php
 <?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\User;
use yii\base\Object;
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

//$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = (string)$model;
?>
<div class="site-resetPassword">



<div class="login_form clearfix col-md-4 col-sm-6 col-xs-12 login-design">


  <?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success') ?>
</div>
<?php endif; ?>
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error') ?>
</div>
<?php endif; ?>

<h1 class="text-center white"><?= Html::encode($this->title) ?></h1>


    
    <p class="text-center white">Please fill out your email. A link to reset password will be sent there.</p>
<div class="form-signin" >
   
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email')->label(false)->textInput(['placeholder'=>'Email']) ?>


                <div class="form-group">
                
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary btn-block']) ?>
               
                </div>
          
</div>
</div>
</div>
<?php ActiveForm::end(); ?>
</div>
</div>
</div>
</div>
 

protected/views/user/resetpassword.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

// $this->title = 'Change Password';
$this->params ['breadcrumbs'] [] = ( string ) $model;
?><br>
<br>
<br>
<br>

<div class="container">
<?php if (Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
    <?php echo Yii::$app->session->getFlash('success')?>
</div>
<?php endif; ?>
<?php if (Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-danger">
    <?php echo Yii::$app->session->getFlash('error')?>
</div>
<?php endif; ?>

	<div
		class="login_form clearfix col-md-4 col-sm-6 col-xs-12 login-design">
		<h1 class="text-center white">Change-Password | Taxi-sitio</h1>



		<br>

		<p class="text-center white">Please fill out the following fields to
			change password :</p>
		<br>
   
    <?php
				
				$form = ActiveForm::begin ( [ 
						'id' => 'changepassword-form',
						'options' => [ 
								'class' => 'form-horizontal' 
						],
						'fieldConfig' => [ 
								'template' => "{label}\n<div class=\"col-lg-12\">
                        {input}</div>\n<div class=\"col-lg-5\">
                        {error}</div>",
								'labelOptions' => [ 
										'class' => 'col-lg-2 control-label' 
								] 
						] 
				] );
				?>
				
				
         <?=$form->field ( $model, 'password', [ 'inputOptions' => [ 'placeholder' => 'Password' ] ] )->label(false)->passwordInput ()?>
          
      
        
       
        <div class="clearfix">
			<div class="">
                <?=Html::submitButton ( 'Change password', [ 'class' => 'btn btn-lg btn-success btn-block' ] )?>
            </div>
		</div>
    <?php ActiveForm::end(); ?>
</div>
</div>
</div>